# Generated by Django 2.2 on 2021-06-26 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kitchen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('image', models.ImageField(upload_to='img')),
            ],
        ),
    ]
