# Generated by Django 2.2 on 2021-06-26 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitchen',
            name='image',
        ),
    ]
